package dev.mtgplay.core.definition

import dev.mtgplay.core.identity.ObjectId
import dev.mtgplay.core.state.GameState

/**
 * The size of a continuous effect's numeric contribution — a layer-7c power/toughness modifier in
 * the MVP pool (CR 613.3, sublayer 7c). Additive, flagged core (P4.1).
 *
 * A [Fixed] amount is a constant printed on the card (Rancor's +2/+0). A [Dynamic] amount is a
 * **pure function of the current game state** (Ethereal Armor's +N/+N, N = enchantments you
 * control), following the ADR-009 pattern used by [ResolutionEffect]: core states *what* the
 * amount is a function of, `mtg-rules` decides *when* to evaluate it. Crucially it is **not** a
 * snapshot — the value is read from the live state every time characteristics are computed
 * (CR 613.3c: a 7c effect applies continuously), which the compute-on-read layer engine gives for
 * free (docs/design/layer-system.md §2, §5).
 */
sealed interface Magnitude {
    /** A constant amount (CR 613.3): the printed modifier of a fixed-bonus Aura. */
    data class Fixed(
        val amount: Int,
    ) : Magnitude

    /**
     * An amount computed from the current [GameState] (CR 613.3c) — a pure function of state and
     * the effect's [source] object, never a snapshot. `mtg-rules` evaluates it against the live
     * state on every characteristic read, so the value tracks the board with no explicit recompute.
     */
    fun interface Dynamic : Magnitude {
        /** The amount right now, from [state], for the effect generated by [source]. */
        fun evaluate(
            state: GameState,
            source: ObjectId,
        ): Int
    }

    companion object {
        /** The absent modifier: a [Fixed] zero, the default for an effect that changes no P/T. */
        val Zero: Magnitude = Fixed(0)
    }
}
