package dev.mtgplay.pauper

/**
 * The card pool: the [CardCatalog] parsed from the bundled Scryfall snapshot
 * (`scryfall-mvp.json`), loaded once (P6.1).
 *
 * The snapshot is the staged, offline card-data source: the union of the MVP pool and every
 * distinct card across the thirteen gauntlet 75s (227 cards, CC BY 4.0, its attribution embedded
 * and surfaced via [CardCatalog.attribution]). It is regenerated by
 * `tools/fetch_scryfall_snapshot.py`, which derives its card list from the bundled decklist
 * resources, so adding a decklist and re-running the script is the whole update path. Every
 * deck-loading and validation entry point that does not take an explicit catalog resolves against
 * this one.
 */
object MvpCardPool {
    /** The absolute classpath path of the staged snapshot. */
    private const val SNAPSHOT_RESOURCE = "/scryfall-mvp.json"

    /** The parsed snapshot, ingested on first access. */
    val catalog: CardCatalog by lazy { ScryfallIngest.parse(readResourceText(SNAPSHOT_RESOURCE)) }
}
