package dev.mtgplay.core.state

import dev.mtgplay.core.identity.CardRef
import dev.mtgplay.core.identity.ObjectId

/**
 * One continuous effect generated by the **resolution of a spell or ability** (CR 611.2), held in
 * [GameState.timedEffects] until its [duration] expires. Additive, flagged core (`FW-DURATION`,
 * docs/design/duration.md §5.1).
 *
 * The sibling of [dev.mtgplay.core.definition.StaticContinuousEffect], and the reason it is a
 * separate type rather than that one with two extra fields. A static continuous effect is something
 * a card **declares** — it rides on a [dev.mtgplay.core.definition.CardDefinition], is active
 * exactly while its source permanent is on the battlefield, and needs neither timestamp nor
 * duration. This is something the game **contains** at a moment in time: it has no permanent behind
 * it, it outlives the object that created it, and it ends on a clock. So it lives in `core/state`
 * beside the other things a [GameState] holds, not in `core/definition`.
 *
 * **The magnitudes are plain integers, and that is the whole snapshot ruling** (CR 608.2h,
 * CR 611.2d, docs/design/duration.md §3). A spell or ability that sets a value using a variable
 * calculates it **once, on resolution**, and the continuous effect it creates uses that calculated
 * value for its whole duration — Basilisk Gate's and Timberwatch Elf's "+X/+X, where X is the number
 * of …" does not grow when a further permanent arrives. That is the opposite of
 * [dev.mtgplay.core.definition.Magnitude.Dynamic], which reads the live board on every
 * characteristic computation (CR 613.3c) and is correct for Ethereal Armor. Storing an `Int` rather
 * than a `Magnitude` makes reusing the dynamic semantics here a **type error** instead of a review
 * catch: there is nowhere to put a state-reading function. The count itself is performed by the
 * resolution effect that creates this, which is exactly where CR 608.2h puts it.
 *
 * **Core/rules split (ADR-009).** This is the record of what was created; classifying it into
 * CR 613 layers, applying it, ordering it against other effects, and ending it at CR 514.2 are all
 * `mtg-rules`.
 *
 * @property affected the one object the effect modifies (CR 611.2c). The affected set is fixed when
 *   the effect begins, so it is a single id rather than a selector: the target the CR 608.2b
 *   re-check had just confirmed. The object may since have left the battlefield — the effect then
 *   applies to nothing for the rest of its duration and is **not** an error, because the object that
 *   comes back is a different one (CR 400.7).
 * @property modification what the effect does — the layer-6 grants and the already-snapshotted
 *   layer-7c modifiers (see [ContinuousModification]).
 * @property duration how long the effect lasts (CR 611.2, CR 613.7d).
 * @property timestamp the effect's CR 613.7d timestamp, drawn from the same strictly monotonic
 *   allocation sequence as [ObjectId]s so that it orders in **one** total sequence against an Aura's
 *   battlefield-entry timestamp (docs/design/duration.md §4). Two independent counters would produce
 *   values that cannot be compared, and CR 613.7 needs a single order within a layer.
 * @property createdOnTurn the [Turn.number] this effect was created on. Stored so the duration
 *   contract is machine-checkable: an [EffectDuration.UntilEndOfTurn] effect surviving into a later
 *   turn means the CR 514.2 wear-off failed, and nothing else in the state records when it began.
 * @property source the object whose resolution created the effect, as last-known information
 *   (CR 113.7c); `null` where the engine has none. Narration and replay only — the effect does not
 *   depend on the source still existing.
 * @property sourceCard the printed identity behind [source] (CR 113.7c), which resolves from the
 *   definition registry whatever zone the source has since reached.
 */
data class TimedContinuousEffect(
    val affected: ObjectId,
    val modification: ContinuousModification,
    val duration: EffectDuration,
    val timestamp: Long,
    val createdOnTurn: Int,
    val source: ObjectId?,
    val sourceCard: CardRef,
) {
    init {
        require(timestamp >= 0) { "CR 613.7d: a timestamp is non-negative, was $timestamp" }
        require(createdOnTurn >= 1) { "CR 500: a turn number is at least 1, was $createdOnTurn" }
    }
}
