package dev.mtgplay.core.state

import dev.mtgplay.core.identity.CardRef
import dev.mtgplay.core.identity.ObjectId

/**
 * One **global** continuous effect generated by the resolution of a spell or ability (CR 611.2) that
 * is read at the CR 615 damage-prevention application point, held in
 * [GameState.preventionEffects] until its [duration] expires. Additive, flagged core (`FW-PREVENT2`).
 *
 * The sibling of [TimedContinuousEffect], and a separate type for one reason: that one names an
 * [TimedContinuousEffect.affected] object and classifies into a CR 613 layer, and neither is true
 * here. See [PreventionEffect] for the full argument.
 *
 * **No timestamp, and its absence is a ruling rather than an omission.** CR 613.7d timestamps exist to
 * order effects *within a layer* when one depends on another's output. Prevention effects do not
 * compose: CR 615.9's disabler is not "later" than a shield, it makes every shield fail to apply
 * whenever either was created, and two shields on two colours neither conflict nor combine — damage is
 * prevented if **any** applicable shield catches it. So there is nothing an order could decide, and
 * carrying a number nothing reads would invite a future reader to believe it means something. The
 * first prevention effect whose outcome depends on which came first must add one.
 *
 * **Core/rules split (ADR-009).** This is the record of what was created; consulting it when damage
 * would be dealt and ending it at CR 514.2 are both `mtg-rules`.
 *
 * @property effect what this effect does at the prevention application point.
 * @property duration how long it lasts (CR 611.2). Both printings in the gauntlet are "this turn"
 *   (CR 514.2), and the type is shared with [TimedContinuousEffect] so the cleanup step ends both
 *   through one exhaustive `when`.
 * @property createdOnTurn the [Turn.number] this effect was created on, stored so the duration
 *   contract is machine-checkable exactly as [TimedContinuousEffect.createdOnTurn] is: an
 *   [EffectDuration.UntilEndOfTurn] effect surviving into a later turn means the CR 514.2 wear-off
 *   failed.
 * @property source the object whose resolution created the effect, as last-known information
 *   (CR 113.7c); `null` where the engine has none. Narration and replay only.
 * @property sourceCard the printed identity behind [source] (CR 113.7c), which resolves from the
 *   definition registry whatever zone the source has since reached.
 */
data class TimedPreventionEffect(
    val effect: PreventionEffect,
    val duration: EffectDuration,
    val createdOnTurn: Int,
    val source: ObjectId?,
    val sourceCard: CardRef,
) {
    init {
        require(createdOnTurn >= 1) { "CR 500: a turn number is at least 1, was $createdOnTurn" }
    }
}
